version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dotwar_root_password01#!
      MYSQL_DATABASE: dotwar_db
      MYSQL_USER: dotwar_server
      MYSQL_PASSWORD: dotwar_password01#!
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql