CREATE TABLE IF NOT EXISTS r (
  id INT NOT NULL AUTO_INCREMENT,
  name FLOAT(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v (
  id INT NOT NULL AUTO_INCREMENT,
  name FLOAT(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS a (
  id INT NOT NULL AUTO_INCREMENT,
  name FLOAT(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pending (
  id INT NOT NULL AUTO_INCREMENT,
  name FLOAT(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_log (
  id INT NOT NULL AUTO_INCREMENT,
  gameId INT NOT NULL,
  createdAt INT NOT NULL,
  content INT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS entity (
  id INT NOT NULL AUTO_INCREMENT,
  gameId INT NOT NULL,
  myName VARCHAR(32) NOT NULL,
  captain VARCHAR(32) NOT NULL,
  r INT NOT NULL,
  v INT NOT NULL,
  a INT NOT NULL,
  entity_type VARCHAR(11) NOT NULL,
  pending INT NOT NULL,
  team INT NOT NULL,
  created_on DATETIME NOT NULL,
  authcode VARCHAR(11) NOT NULL,
  captured VARCHAR(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS game (
  id INT NOT NULL AUTO_INCREMENT,
  myName FLOAT(11) NOT NULL,
  created_on DATETIME NOT NULL,
  last_modified DATETIME NOT NULL,
  server_time DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
